package visao;

import controle.ConectaBanco;
import controle.ControlaContas;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import modelo.MConta;
import modelo.MTabela;

public class VCadastroConta extends javax.swing.JFrame {

    MConta conta = new MConta();
    ControlaContas adicionaConta = new ControlaContas();
    ConectaBanco conexao = new ConectaBanco();
    
    
    

    String nome;
    String tipoConta;
    double valorTitulo;
    double valorJuros;
    int numeroParcelas;
    String dataCadastro;
    String dataVencimento;

    public String getTxtNomeTitulo() {
        return txtNomeTitulo.getText();
    }

    public String getCbTipoConta() {
        return cbTipoConta.getSelectedItem().toString();
    }

    public void setCbTipoConta(JComboBox<String> cbTipoConta) {
        this.cbTipoConta = cbTipoConta;
    }

    public void setTxtNomeTitulo(String txtNomeTitulo) {
        this.txtNomeTitulo.setText(txtNomeTitulo);
    }

    public String getTxtNumeroParcelas() {
        return txtNumeroParcelas.getText();
    }

    public void setTxtNumeroParcelas(String txtNumeroParcelas) {
        this.txtNumeroParcelas.setText(txtNumeroParcelas);
    }

    public String getTxtValorJuros() {
        return txtValorJuros.getText();
    }

    public void setTxtValorJuros(String txtValorJuros) {
        this.txtValorJuros.setText(txtValorJuros);
    }

    public String getTxtValorTitulo() {
        return txtValorTitulo.getText();
    }

    public void setTxtValorTitulo(String txtValorTitulo) {
        this.txtValorTitulo.setText(txtValorTitulo);
    }

    public String getJdcDatacadastramento() {
        return jDataCadastramento.getDate().toLocaleString();
    }

    public void setJdcDataCadastramento(String jdcDataCadastramento) {
        this.jDataCadastramento.setDate(null);
    }

    public String getJdcDataVencimento() {
        return jDataVencimento.getDate().toLocaleString();
    }

    public void setJdcDataVencimento(String jdcDataVencimento) {
        this.jDataVencimento.setDate(null);
    }

    public void setValues() {
        conta.setNome(nome);
        conta.setTipoTitulo(tipoConta);
        conta.setValor(valorTitulo);
        conta.setJurosDia(valorJuros);
        conta.setNumeroParcelas(numeroParcelas);
        conta.setJdcDataCadastro(dataCadastro);
        conta.setJdcDataVencimento(dataVencimento);
    }

    public VCadastroConta() {
        initComponents();
    }

    public boolean validacao() {

        if (getTxtNomeTitulo() == null || getTxtNomeTitulo().isEmpty() || "0".equals(getTxtNomeTitulo())) {
            JOptionPane.showMessageDialog(null, "Preencha o Nome da Conta para continuar", "Aviso", JOptionPane.WARNING_MESSAGE);
            txtNomeTitulo.requestFocus();
            this.setVisible(true);
        }

        if (getTxtValorTitulo() == null || getTxtValorTitulo().isEmpty() || "0".equals(getTxtValorTitulo())) {
            JOptionPane.showMessageDialog(null, "Preencha o Valor do Título para continuar.", "Aviso", JOptionPane.WARNING_MESSAGE);
            txtValorTitulo.requestFocus();
            this.setVisible(true);
        }

        if (getTxtValorJuros() == null || getTxtValorJuros().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha o Valor do Juros para continuar. Caso não tenha coloque 0", "Aviso", JOptionPane.WARNING_MESSAGE);
            txtValorJuros.requestFocus();
            this.setVisible(true);
        }

        if (getTxtNumeroParcelas() == null || getTxtNumeroParcelas().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha o Numero de Parcelas para continuar. Caso não tenha coloque 0 ", "Aviso", JOptionPane.WARNING_MESSAGE);
            txtNumeroParcelas.requestFocus();
            this.setVisible(true);
        }

        if (getJdcDatacadastramento() == null || getJdcDatacadastramento().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha o Data de Cadastramento para continuar", "Aviso", JOptionPane.WARNING_MESSAGE);
            jDataCadastramento.requestFocus();
            this.setVisible(true);
        }

        if (getJdcDataVencimento() == null || getJdcDataVencimento().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha a Data de Vencimento para continuar", "Aviso", JOptionPane.WARNING_MESSAGE);
            jDataVencimento.requestFocus();
            this.setVisible(true);
        }

        return true;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNomeTitulo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtValorTitulo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtValorJuros = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtNumeroParcelas = new javax.swing.JTextField();
        cbTipoConta = new javax.swing.JComboBox<String>();
        jLabel7 = new javax.swing.JLabel();
        jDataCadastramento = new com.toedter.calendar.JDateChooser();
        jDataVencimento = new com.toedter.calendar.JDateChooser();
        btnCancelar = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro de Titulo", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel1.setText("Nome");

        txtNomeTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeTituloActionPerformed(evt);
            }
        });

        jLabel2.setText("Data de cadastramento");

        jLabel3.setText("Valor");

        jLabel4.setText("Data de Vencimento");

        jLabel5.setText("Valor do Juros");

        txtValorJuros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorJurosActionPerformed(evt);
            }
        });

        jLabel6.setText("Numero de parcelas");

        cbTipoConta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Boleto", "Carnê", "Cheque", "Outras Despezas" }));
        cbTipoConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoContaActionPerformed(evt);
            }
        });

        jLabel7.setText("Tipo de conta");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(txtNomeTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(cbTipoConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jDataCadastramento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(118, 118, 118)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jDataVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(txtValorTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(51, 51, 51)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtValorJuros, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(41, 41, 41)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtNumeroParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNomeTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbTipoConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtValorTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtValorJuros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNumeroParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDataCadastramento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDataVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCadastrar)
                .addGap(32, 32, 32)
                .addComponent(btnCancelar)
                .addGap(115, 115, 115))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(btnCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void txtNomeTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeTituloActionPerformed

    private void cbTipoContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoContaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTipoContaActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed

        this.dispose();


    }//GEN-LAST:event_btnCancelarActionPerformed


    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        if (validacao()) {
            try {
                //objeto df configura data para a data desejada
                DateFormat df = new SimpleDateFormat("dd/MM/yyyy");

                
                nome = txtNomeTitulo.getText();
                tipoConta = cbTipoConta.getSelectedItem().toString();
                valorTitulo = Double.parseDouble(getTxtValorTitulo());
                valorJuros = Double.parseDouble(getTxtValorJuros());
                numeroParcelas = Integer.parseInt(getTxtNumeroParcelas());
                dataCadastro = df.format(jDataCadastramento.getDate());
                dataVencimento = df.format(jDataVencimento.getDate());

                setValues();
                adicionaConta.adicionarConta(conta);
                JOptionPane.showMessageDialog(null, "Cadastrado com Sucesso.", "Aviso", JOptionPane.WARNING_MESSAGE);
                this.setVisible(false);
                
                

            } catch (SQLException ex) {
                Logger.getLogger(VCadastroConta.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        
       
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void txtValorJurosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorJurosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorJurosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VCadastroConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VCadastroConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VCadastroConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VCadastroConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VCadastroConta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox<String> cbTipoConta;
    private com.toedter.calendar.JDateChooser jDataCadastramento;
    private com.toedter.calendar.JDateChooser jDataVencimento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtNomeTitulo;
    private javax.swing.JTextField txtNumeroParcelas;
    private javax.swing.JTextField txtValorJuros;
    private javax.swing.JTextField txtValorTitulo;
    // End of variables declaration//GEN-END:variables

}
